### ISSUE TITLE
Need SVG version of Robot Framework icon for VS Code Icons

### ISSUE THREAD

**Issue by GLMeece** [robotframework/visual-identity#2]
# Issue

[VS Code icons](https://github.com/vscode-icons/vscode-icons/wiki/ListOfFiles#robotframework) references [a _very_ old version of the Robot Framework logo](https://raw.githubusercontent.com/vscode-icons/vscode-icons/master/icons/file_type_robotframework.svg?sanitize=true). In order to make a pull request for this icon set, an SVG version is needed. 

## Details

Rather than attempting to create a version myself from the existing PNG and PDF assets, it is suggested that the Robot Framework Foundation supply a **S**calable **V**ector **G**raphics (**SVG**) as part of the assets set, which can subsequently be supplied for a Pull Request to VS Code Icons, etc.

**Comment by pekkaklarck** [comment]
It's easy to create SVG version based on the PDF version. I can do that so that others don't need to.

**Comment by GLMeece** [comment]
Thanks @pekkaklarck ! I've submitted [a Pull Request](https://github.com/vscode-icons/vscode-icons/pull/2031) to their project.
